### ISSUE TITLE
Néhány észrevétel a dokumentációhoz

### ISSUE THREAD

**Issue by SakiiCode** [boapps/e-kreta-api-docs#1]
- Az apiKey mindenkinek ugyanaz, kötelező a lekérdezéshez, gondolom hardcode-olva van mindenbe

- Content-Type, Host, Accept, stb hasonló értelmetlen headerek nem kötelezőek

- Lehet a normál tokent felh.név-jelszó nélkül is frissíteni az eredeti bejelentkezésnél kapott refresh_tokennel
`institute_code=XXXXXXXXXXXX&client_id=919e0c1c-76a2-4646-a2fb-7085bbbf3c56&refresh_token=XXXXXXXXXXXX&grant_type=refresh_token`

- ugyanitt értelemszerűen a grant_type= password vagy refresh_token lehet

- a client_id pedig mindenkinél ugyanaz és kötelező, gondolom hardcode-olva van ez is

- A választ tömörített formában is kérhetjük az "Accept-Encoding: gzip" headerrel. Adatforgalom spóroláshoz és sebességnöveléshez jó.

- A kréta alkalmazás elküldi a telefonunk típusát, meg még dolgokat User-Agent formájában. Nem szép dolog.

Kitartást!

**Comment by boapps** [comment]
Köszi a visszajelzést! Majd kijavitgatom amiket írtál. Amúgy volt amikor a hockeyappos telemetryben a diák nevét és iskoláját is küldte (szóltam és javították).
