### ISSUE TITLE
502hiba Bearer key

### ISSUE THREAD

**Issue by Detry01** [boapps/e-kreta-api-docs#10]
502-es hibát dob, amikor requestelni akarom a kulcsomat.  :P

**Comment by boapps** [comment]
Lehet, hogy amikor próbáltad, épp valami hiba volt a Krétás apival, esetleg most próbáld újra. De ez szerintem nem a dokumentációval kapcsolatos, hanem a kréta szerveroldali cuccával lehet valami. Böngészős felületről/mobil appból beengedett?

**Comment by Detry01** [comment]
Szerintem is a krétás apival van probléma, de azért köszi ^^ 👍

**Comment by Detry01** [comment]
Most se működik szóval szerintem is a kréta apival van probléma, de azért köszi ^^ 👍 Mindkettőről beenged

**Comment by boapps** [comment]
@Detry01 Ha mindkettőről beenged az érdekes, mert a mobil kréta app pontosan ezt a lekérdezést használja, biztos jól írtad be a curl parancsot?

**Comment by Detry01** [comment]
A curl biztos, hogy nomrálisan van kitöltve szóval nem tudom mi lehet a probléma.

**Comment by palmarci** [comment]
jó oké srácok ugye azt tudjátok mit jelent az 502?

**Comment by Detry01** [comment]
bad gateway :/

**Comment by boapps** [comment]
Ez a hiba még mindig nem oldódott meg?

**Comment by Detry01** [comment]
Ja, igazából már aznap megoldottam :P
