### ISSUE TITLE
Lekérdezéshez milyen encoding van az ékezetes betűkhöz?

### ISSUE THREAD

**Issue by gerokristof09** [boapps/e-kreta-api-docs#11]
Ha a passwordban találhatóak ékezetes betűk, azokat hogyan encodeoljam, hogy ne dobjon "Invalid login name or password" hibát?

**Comment by gerokristof09** [comment]
`curl --data-urlencode` használatával `invalid_client` hibát dob

**Comment by boapps** [comment]
add hozzá ezt a paramétert: `-H "Content-Type: application/x-www-form-urlencoded; charset=utf-8"`

**Comment by boapps** [comment]
A dokumentéációban is javítottam, köszönöm, hogy szóltál!
