### ISSUE TITLE
A grant_type-ról bővebben

### ISSUE THREAD

**Issue by chriskoder** [boapps/e-kreta-api-docs#12]
Kicsit utána olvastam a grant_typenak (a dokumentációban ez egy mystery 😄)
A hitelesítés igazából OAuth 2.0-es "hitelesítési keretrendszer" (fogalmam sincs, hogy ez-e a helyes fordítása az authorization frameworknek) segítségével történik, ami igazából egy protocol (ahogy olvastam).

Több féle grant_type létezik az OAuth 2.0-ban:
   - Authorization Code
   - Implicit 
   - **Password** 
   - Client Credentials
   - Device Code
   - Refresh Token

(a grant_type egyébként egy kötelező paraméter)
És most a lényeg (amiről fogalmam sincs, hogy hogy lehetne helyesen lefordítani értelmes magyarra)
An authorization grant is a credential representing the resource owner's authorization (to access its protected resources) used by the client to obtain an access token.

A `grant_type=password` azt jelenti, hogy felhasználónevet + jelszót küldünk el a /Token "végpontnak".

_Bővebben itt lehet erről az egészről olvasni: https://tools.ietf.org/html/rfc6749_

**Comment by gerokristof09** [comment]
Most találtam hozzá egy magyar nyelvű wiki oldalt, ebből talán jobban érthető:
https://hu.wikipedia.org/wiki/OAuth#OAuth_2.0

**Comment by boapps** [comment]
Wow, szépen utánna néztél, nem is tudtam, hogy ez OAuth 2. Azt tudtam, hogy még `grant_type=refresh_token`-t is lehet csinálni (amikor lekéred a password-el, akkor nem csak access_tokent kapsz, hanem ezt a refresh_tokent is), a KRÉTA alkalmazás is ezt használja. Hátránya, hogy elég valakinek egyszer megszerezni a jelszavadat és utánna hiába változtatod meg, a támadó refreshelgetheti a tokent a végtelenségig és használhatja a felhasználódat. Az ügyfélszolgálatuknak már rég szóltam róla, de nem foglalkoznak vele.

Én utálok fordítani, de holnap megkérdezem egy barátomat, aki büszke tulajdonosa egy C2-es nyevvizsgának. 

A megismert információt pedig hozzáadom a docshoz.

**Comment by chriskoder** [comment]
Lehet, hogy csak - úgy, mint a Telekomos ügynél - akkor kezdenének el foglalkozni vele, hogyha valaki tényleg csinálna valamit, mondjuk lényegesen sok tanári profillal.

**Comment by thegergo02** [comment]
Mondjuk aki plain text belépési adatokat küld _grant\_type=password_-al az bátor. De legalább már ismerjük ezt a részelét is az API-nak.

**Comment by boapps** [comment]
@thegergo02 A kommunikáció https protokolon megy, szóval olyan értelemben nem plaintext.

**Comment by danielszenasi** [comment]
A jwt token lenyege, hogy a szerver egy titkos kulccsal titkositja a json-t, aminek tartalmat utana a kliens siman vissza tudja fejteni peldaul itt https://jwt.io meg tudod nezni  ha bemasolod a kapott access tokent. 
Szoval a szerver nem menti el ezt az access tokent adatbazisba csak annyit tud megmondani, hogy a szerver allitotta-e ki. es ugye a kliens nem tudja modositani a json tartalmat, mert ujra titkositani kellene, igy a szerver biztos lehet benne, hogy a json tartalma megbizhato

a hatranya hogy az access tokent nem mentjuk el adatbazisba az hogy nem lehet ervenyteleniteni es ezt szoktak ugy megoldani, hogy az access tokennek van egy lejarata es a refresh token pedig olyan amit elmentenek adatbazisba es igy ki lehet zarni emberket a redszerbol, ha a refres tokenjet torlik az adatbazisbol
