### ISSUE TITLE
Refresh token használata

### ISSUE THREAD

**Issue by pepyta** [boapps/e-kreta-api-docs#20]
A dokumentáció nem ad egyértelmű választ arra, hogy mikor szükséges az access_token frissítése: amikor amiatt, mert lejárt visszautasítja vagy ezt folyamatosan kell frissíteni?

**Comment by thegergo02** [comment]
Ha lejárt, akkor tudsz egy új access token-t kapni a refresh_tokennel. De ez levan írva (szerintem) egyértelműen.

**Comment by thegergo02** [comment]
Kapsz egy `expires_in` értéket is mindig, az alapján frissíthetsz.

**Comment by pepyta** [comment]
Rendben, köszönöm szépen!
