### ISSUE TITLE
Átlagok nem elérhetőek.

### ISSUE THREAD

**Issue by thegergo02** [boapps/e-kreta-api-docs#22]
Lehet az én iskolám hibája, de én se kapok vissza semmit, se a~~z eSzivacs~~ Szivacs Napló.

**Comment by boapps** [comment]
Igen láttam, már csütörtök óta ilyen, egyszer majd úgyis megcsinálják a krétások (a hivatalos appban is ilyen) én addig azt fogom csinálni, hogy a jegyekből kiszámolom az átlagot.

**Comment by thegergo02** [comment]
Újra elérhetőek.
