### ISSUE TITLE
Bearer api (client_id) kód?

### ISSUE THREAD

**Issue by Legolaszstudio** [boapps/e-kreta-api-docs#23]
Üdv!

Viszonylag érhető a krétások blokkolásos dolga számomra, viszont azt nem igazán értem, hogy amikor a bearer-t kérjük le, akkor miért használunk egységes api kódot, és ez egyáltalán engedélyezett-e jelenleg?

Ugye itt van az api kód a lekérésben:
`curl --data "institute_code=xxxxxxxxxxx&userName=xxxxxxxxxxx&password=xxxxxxxxxxx&grant_type=password&client_id=`**919e0c1c-76a2-4646-a2fb-7085bbbf3c56**`" https://xxxxxxxxxxx.e-kreta.hu/idp/api/v1/Token -H "Content-Type: application/x-www-form-urlencoded; charset=utf-8"`
Ezt lehet használni, ezzel nincs semmi probléma?

És ezt nem lehet használni ilyen formában: `-H "User-Agent:`**Kreta.Ellenorzo**", ha jól értelmeztem, akkor a **Kreta.Ellenorzo**-t kell kicserélni valami másra, ugye? Meg szintén nem lehet iskola listát és intézmény információt lekérni "legálisan"?

**Barátságos emlékezetető**: A commit előzményeidet nem törölted, aki akarja még vissza tudja keresni a "tiltott" api kulcsukat.
[https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github](https://stackoverflow.com/questions/13716658/how-to-delete-all-commit-history-in-github)

**Comment by palmarci** [comment]
Mindent összeszedtünk és frissítettünk:
https://github.com/boapps/e-kreta-api-docs

**Comment by Legolaszstudio** [comment]
Köszönöm 👍
