### ISSUE TITLE
Segítség a leckék lekérdezéséhez

### ISSUE THREAD

**Issue by thegergo02** [boapps/e-kreta-api-docs#3]
Ha jól veszem észre, a lecke adatai benne vannak az órarend lekérdezésben. Elég gyanúsak a
`   "TeacherHomeworkId": null,
    "IsTanuloHaziFeladatEnabled": true,
    "Homework": null`
változók. Nekem nem írják be ide a leckéket, szóval nem tudom mit tárolnak ezek.

**Comment by boapps** [comment]
A TeacherHomeworkId-ben kéne lenni egy id-nek és azt egy másik lekérdezésben (amit majd felrakok ide). Van egy alkalmazásom (e-Szivacs 2) ott benne van minden tudás, amit összegyűjtöttem.

**Comment by thegergo02** [comment]
Azt hittem nincs meg rá a megoldás :) Rendben akkor rakd fel ide hogy más is megtalálja. ("A szivacs letörli a krétát")

**Comment by boapps** [comment]
Bár az ID-nek nem null-nak kéne lennie

**Comment by thegergo02** [comment]
@boapps Szerintem zárhatod az issue-t, hisz hozzá lett adva a dokumentációhoz.
