### ISSUE TITLE
A "Nem tudom mit csinál" request.

### ISSUE THREAD

**Issue by thegergo02** [boapps/e-kreta-api-docs#4]
Szerintem az API linket kéri le, szóval ha változna bármikor is, nem kell új release kiadni.

**Comment by Xerren09** [comment]
Nembiztos, hogy segítek, de szerintem ez így nem igaz. A linkek amiket visszadob nem a felhasználóknak szólnak a rövidítések alapján:
GlobalMobileApiUrlDEV - Belső fejlesztői renszerhez a link (DEV)
GlobalMobileApiUrlTEST- Valószínüleg egy sandbox verzió linkje tesztelésre (TEST)
GlobalMobileApiUrlUAT - User Acceptance Testing, lényegében egy béta verziós rendszer linkje (UAT)
GlobalMobileApiUrlPROD - A belső hálózatuk rendszerének linkje (PROD - production)
Lényegében ezek közül egyik sem nekünk szánt link, és amennyire láttam nem is használja őket a program. Valószínüleg csak valami visszamardt debug tool részletről lehet szó.

**Comment by boapps** [comment]
@Xerren09 Abban biztos igazad van, hogy az uat, dev és test azok a tesztelős api linkek, de azokat is azért így szedi le, hogy lehessen dinamikusan váltani. Mellesleg a PROD (production) az nekünk van ott, az nem tesztre szánt.
Régen egyébként be lehetett bugoltatni az appot (valami activity launcher-rel megnyitottam az update activity-t) és akkor letöltötte apk-ként a legújabb debug verziót, amit a kréta használt belső tesztekre, már sajnos nem megy. Egy hockeyapp nevezetű rendszert használnak telemetry-re, bug reporting-re és zárt, belső béta tesztekre.

**Comment by Xerren09** [comment]
Igen, közben jobban belenéztem, a prod-ot használja, de a mostani kiadott verzió csak azt tudja kezelni. Valószínüleg a fogalmazás kavart meg jobban, mert nem az API url esetleges változása miatt van az ott, hanem teszteknél való váltáshoz. Használtam már ilyet, egy ilyen hibrid verzió néha kell, de soha nem (lenne) szabad benne hagyni a végső releaseben.
_Ez most szíven ütött. Eddig is tudtam, hogy silány tervezésű a rendszer, de hogy benne hagytak védett hozzáférésű részlegeket nyíltan a végleges appban..._

**Comment by boapps** [comment]
Ezt azóta javítottam.
